language: node_js

node_js:
  - "6"

after_success:
  #- bash <(curl -s https://scripts.scantist.com/staging/ci-travis.sh)
  - curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
  - java -jar scantist-bom-detect.jar --debug
  - cat dependency-tree.json
  - cat scantist_report.log
